### ISSUE TITLE
Anteproyecto: Sobre algoritmos

### ISSUE THREAD

**Issue by harpomaxx** [CarlosPerezVE/ia-uncuyo-2021#2]
Se podrian especificar algun algoritmo a utilizar. Por ejemplo Policy Gradient (mas alla de que despues no resulte adecuado). Tambien en una segunda etapa y si alcanza el tiempo se podria probar algun algoritmo de Deep Learning como DQN

**Comment by cepmcs** [comment]
Agregado al ante-proyecto el algoritmo elegido (Q learning) y en caso de que alcance el tiempo, un análisis  del DQN y su comparación con el Q learning.
